package pkl54.capi.subseksi.pkl54.Questionnaire.FragmentPresenter;

/**
 * Created by EKI on 19/02/2015.
 */
public interface OnFinishValidateBlok3 {
    public void setEnableB3R2();
    public void setEnableB3R3();
    public void setEnableB3R4();
    public void setEnableB3R5();
    public void setEnableB3R6();
    public void setEnableB3R7();
    public void setEnableB3R8();
    public void setEnableB3R9();
    public void setEnableB3R10();
    public void setEnableB3R11();
    public void setEnableB3R12();
    public void setEnableB3R13();
    public void setEnableB3R14();
    public void setDisableB3R2();
    public void setDisableB3R3();
    public void setDisableB3R4();
    public void setDisableB3R5();
    public void setDisableB3R6();
    public void setDisableB3R7();
    public void setDisableB3R8();
    public void setDisableB3R9();
    public void setDisableB3R10();
    public void setDisableB3R11();
    public void setDisableB3R12();
    public void setDisableB3R13();
    public void setDisableB3R14();
    public void setVisibleB3R1();
    public void setInvisibleB3R1();
    public void setVisibleB3R2();
    public void setInvisibleB3R2();
    public void setVisibleB3R3();
    public void setInvisibleB3R3();
    public void setVisibleB3R4();
    public void setInvisibleB3R4();
    public void setVisibleB3R5();
    public void setInvisibleB3R5();
    public void setVisibleB3R6();
    public void setInvisibleB3R6();
    public void setVisibleB3R7();
    public void setInvisibleB3R7();
    public void setVisibleB3R8();
    public void setInvisibleB3R8();
    public void setVisibleB3R9();
    public void setInvisibleB3R9();
    public void setVisibleB3R10();
    public void setInvisibleB3R10();
    public void setVisibleB3R11();
    public void setInvisibleB3R11();
    public void setVisibleB3R12();
    public void setInvisibleB3R12();
    public void setVisibleB3R13();
    public void setInvisibleB3R13();
    public void setVisibleB3R14();
    public void setInvisibleB3R14();
    public void setEnableB3R8S2RB1();
    public void setDisableB3R8S2RB1();
    public void setEnableB3R8S2RB2();
    public void setDisableB3R8S2RB2();
    public void setEnableB3R8S2RB3();
    public void setDisableB3R8S2RB3();
    public void setEnableB3R8S2RB4();
    public void setDisableB3R8S2RB4();
    public void setUncheckedB3R8S2RB1();
    public void setUncheckedB3R8S2RB2();
    public void setUncheckedB3R8S2RB3();
    public void setUncheckedB3R8S2RB4();
    public void navigateFragment();
}
